<?xml version="1.0"?>

<robot name="swole" xmlns:xacro="http://www.ros.org/wiki/xacro">

	<!-- Import swole XL wheels -->
	<!-- <xacro:include filename="$(find swole_description)/urdf/wheels/omni_wheel.urdf.xacro" /> -->
	<xacro:include filename="$(find swole_description)/urdf/base/swole_base.urdf.xacro" />

	<!-- Import Swole Gripper -->
	<!-- <xacro:include filename="$(find swole_description)/urdf/gripper/gripper.urdf.xacro" /> -->

	<!-- Wheel parameters -->
	<xacro:property name="wheel_offset_x" value="0.1" />    <!-- x,y,z in translation from base_link to the center of the wheel -->
	<xacro:property name="wheel_offset_y" value="0.2" />
	<xacro:property name="wheel_offset_z" value="0.0" />

	<xacro:macro name="robot">
		<xacro:swole_base/>
<!-- 
		<xacro:omni_wheel prefix="swole_front_right" parent="swole_base_link" reflect="false">
			<origin xyz="${wheel_offset_x} -${wheel_offset_y} ${wheel_offset_z}" rpy="0 0 0"/>
		</xacro:omni_wheel>

		<xacro:omni_wheel prefix="swole_front_left" parent="swole_base_link" reflect="true">
			<origin xyz="${wheel_offset_x} ${wheel_offset_y} ${wheel_offset_z}" rpy="0 0 0"/>
		</xacro:omni_wheel>

		<xacro:omni_wheel prefix="swole_back_left" parent="swole_base_link" reflect="true">
			<origin xyz="-${wheel_offset_x} ${wheel_offset_y} ${wheel_offset_z}" rpy="0 0 0"/>
		</xacro:omni_wheel>

		<xacro:omni_wheel prefix="swole_back_right" parent="swole_base_link" reflect="false">
			<origin xyz="-${wheel_offset_x} -${wheel_offset_y} ${wheel_offset_z}" rpy="0 0 0"/>
		</xacro:omni_wheel> -->


		<!-- <xacro:gripper parent="chassis" origin_xyz="${(base_box_x / 2.0) + (gripper_base_x / 2.0)} 0 0"/> -->
		<!-- <xacro:gripper parent="base_link" origin_xyz="0 0 0.02"/> -->


        <xacro:omni_steering/>

   </xacro:macro>

   <xacro:robot/>

</robot>

